# Generated by Django 5.1 on 2024-08-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moeda_1', models.CharField(max_length=3)),
                ('moeda_2', models.CharField(max_length=3)),
                ('conversao', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_venda', models.FloatField(blank=True, null=True)),
                ('valor_compra', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
