# Generated by Django 5.1 on 2024-08-24 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0002_contabancaria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contabancaria',
            old_name='salgo_ARS',
            new_name='saldo_ARS',
        ),
    ]
